// One post. Generated by SearchBlueprint — safe to edit, it is your file now.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getAllPosts, getPostBySlug } from "../../../lib/blog/posts";
import { blogStyles } from "../../../lib/blog/styles";

export const dynamic = "force-static";

// A slug that is not a file in this repository does not exist, so it should 404
// rather than be rendered on demand from a folder the server cannot see.
export const dynamicParams = false;

type RouteParams = { slug: string };

// Next 15 made params a promise. Awaiting one on Next 13 or 14, where it is a
// plain object, returns the object — so this one type is right everywhere.
type PageProps = { params: Promise<RouteParams> };

export const generateStaticParams = async (): Promise<RouteParams[]> =>
  getAllPosts().map((post) => ({ slug: post.slug }));

export const generateMetadata = async ({ params }: PageProps): Promise<Metadata> => {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return {};
  const url = "https://jilian-dashboard.vercel.app/blog/" + post.slug;
  return {
    title: post.title,
    description: post.description,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.description,
      url,
      publishedTime: post.date || undefined,
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
    },
  };
};

const BlogPostPage = async ({ params }: PageProps) => {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) notFound();
  const jsonLd: Record<string, string> = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
  };
  if (post.description) jsonLd.description = post.description;
  if (post.date) {
    jsonLd.datePublished = post.date;
    jsonLd.dateModified = post.date;
  }
  jsonLd.url = "https://jilian-dashboard.vercel.app/blog/" + post.slug;
  return (
    <div>
      <style>{blogStyles}</style>
      <article className="sb-blog">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
        <h1>{post.title}</h1>
        {post.dateLabel ? (
          <time className="sb-blog-meta" dateTime={post.date}>
            {post.dateLabel}
          </time>
        ) : null}
        <div className="sb-blog-body" dangerouslySetInnerHTML={{ __html: post.html }} />
        <Link className="sb-blog-back" href="/blog">
          Back to all posts
        </Link>
      </article>
    </div>
  );
};

export default BlogPostPage;
