// The blog index. Generated by SearchBlueprint — safe to edit, it is your file now.
//
// It renders inside your own layout, so your header, footer, fonts and colours
// apply to it exactly as they do everywhere else on the site.
import type { Metadata } from "next";
import Link from "next/link";
import { getAllPosts } from "../../lib/blog/posts";
import { blogStyles } from "../../lib/blog/styles";

export const metadata: Metadata = {
  title: "Blog",
  description: "Articles, guides and updates.",
  alternates: { canonical: "https://jilian-dashboard.vercel.app/blog" },
};

// Built once, when the site is built. The posts are files in this repository, so
// there is nothing to re-read per request — and reading a file at request time is
// where a file the bundler did not know about becomes a 500 in production.
export const dynamic = "force-static";

const BlogIndexPage = () => {
  const posts = getAllPosts();
  return (
    <div>
      <style>{blogStyles}</style>
      <div className="sb-blog">
        <h1>Blog</h1>
        <p className="sb-blog-lede">Articles, guides and updates.</p>
        {posts.length === 0 ? (
          <p className="sb-blog-empty">No posts yet. The first one will appear here.</p>
        ) : (
          <ul className="sb-blog-list">
            {posts.map((post) => (
              <li key={post.slug} className="sb-blog-item">
                <h2>
                  <Link href={"/blog/" + post.slug}>{post.title}</Link>
                </h2>
                {post.description ? <p>{post.description}</p> : null}
                {post.dateLabel ? (
                  <time className="sb-blog-meta" dateTime={post.date}>
                    {post.dateLabel}
                  </time>
                ) : null}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
};

export default BlogIndexPage;
