// Front matter and markdown, with no dependencies.
//
// Nothing here is imported from npm on purpose. A package would have to be added
// to package.json AND the lockfile in the same commit, and an install that runs
// with a frozen lockfile fails the moment those two disagree. A blog is not
// worth a broken deploy.
//
// Generated by SearchBlueprint. Safe to edit — it is your file now.

export interface FrontMatter {
  [key: string]: string;
}

export interface ParsedDocument {
  data: FrontMatter;
  body: string;
}

const unquote = (value: string): string => {
  const trimmed = value.trim();
  const quoted =
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"));
  if (!quoted || trimmed.length < 2) return trimmed;
  return trimmed.slice(1, -1).replace(/\\"/g, '"').replace(/\\'/g, "'");
};

// Two things here are load-bearing:
//
// A byte-order mark ahead of the opening --- (65279 is that mark) would stop the
// front matter being recognised at all, and the whole post would render as one
// block of text starting with three dashes.
//
// An opening --- that is never closed is NOT front matter. Reading the whole file
// as metadata would render a post with an empty body, which looks like a
// publishing failure rather than the malformed file it is.
export const parseFrontMatter = (raw: string): ParsedDocument => {
  const source = String(raw == null ? "" : raw);
  const text = source.charCodeAt(0) === 65279 ? source.slice(1) : source;
  const lines = text.split(/\r?\n/);
  if (lines.length === 0 || lines[0].trim() !== "---") return { data: {}, body: text };
  const data: FrontMatter = {};
  let closed = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      closed = i;
      break;
    }
    const colon = lines[i].indexOf(":");
    if (colon <= 0) continue;
    const key = lines[i].slice(0, colon).trim();
    if (key) data[key] = unquote(lines[i].slice(colon + 1));
  }
  if (closed === -1) return { data: {}, body: text };
  return { data, body: lines.slice(closed + 1).join("\n").replace(/^\n+/, "") };
};

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

// Only addresses a browser can safely follow. Without this, a link written as
// [read more](javascript:...) inside a post would be a script-injection vector on
// your own domain.
const safeUrl = (url: string): string | null => {
  const trimmed = url.trim();
  if (/^https?:/i.test(trimmed)) return trimmed;
  if (/^mailto:/i.test(trimmed)) return trimmed;
  if (/^[/#]/.test(trimmed)) return trimmed;
  return null;
};

// Markdown allows HTML inside it, and the articles this publishes use it —
// <figure>/<figcaption> around charts, the odd <strong> mid-sentence. Escaping
// all of it printed the raw tags on the published page as body text, so the same
// article read correctly everywhere else and broken here.
//
// So: recognised markup passes through, everything else is escaped and therefore
// visible but inert. <script>, <style> and <iframe> are deliberately NOT on this
// list — an embed you add yourself is one line away, and a page on your own
// domain that runs whatever a post file happens to contain is not.
const ALLOWED_TAGS = new Set([
  "a", "abbr", "article", "aside", "b", "blockquote", "br", "caption", "cite", "code",
  "col", "colgroup", "dd", "del", "details", "div", "dl", "dt", "em", "figcaption",
  "figure", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hr", "i", "img",
  "ins", "kbd", "li", "main", "mark", "nav", "ol", "p", "picture", "pre", "q", "s",
  "samp", "section", "small", "source", "span", "strong", "sub", "summary", "sup",
  "table", "tbody", "td", "tfoot", "th", "thead", "time", "tr", "u", "ul", "var", "wbr",
]);

// An allowed tag carrying onclick="" is still a script, so attributes are an
// allowlist too. Everything absent here is dropped rather than rewritten.
const ALLOWED_ATTRIBUTES = new Set([
  "alt", "cite", "class", "colspan", "datetime", "dir", "height", "href", "id", "lang",
  "loading", "reversed", "rowspan", "span", "src", "srcset", "start", "title", "type", "width",
]);

const URL_ATTRIBUTES = new Set(["href", "src", "cite"]);

const VOID_TAGS = new Set(["br", "col", "hr", "img", "source", "wbr"]);

const ATTRIBUTE = /([a-zA-Z_:][a-zA-Z0-9_.:-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>]+)))?/g;

const sanitizeTag = (raw: string): string => {
  const closing = /^<\s*\/\s*([a-zA-Z][a-zA-Z0-9-]*)\s*>$/.exec(raw);
  if (closing) {
    const name = closing[1].toLowerCase();
    return ALLOWED_TAGS.has(name) ? "</" + name + ">" : escapeHtml(raw);
  }
  const opening = /^<\s*([a-zA-Z][a-zA-Z0-9-]*)/.exec(raw);
  if (!opening) return escapeHtml(raw);
  const name = opening[1].toLowerCase();
  if (!ALLOWED_TAGS.has(name)) return escapeHtml(raw);
  const attributes: string[] = [];
  const body = raw.slice(opening[0].length).replace(/\/?>$/, "");
  let attribute: RegExpExecArray | null;
  ATTRIBUTE.lastIndex = 0;
  while ((attribute = ATTRIBUTE.exec(body)) !== null) {
    const key = attribute[1].toLowerCase();
    if (!ALLOWED_ATTRIBUTES.has(key)) continue;
    let value = attribute[2] !== undefined ? attribute[2] : attribute[3];
    if (value === undefined) value = attribute[4];
    if (value === undefined) value = "";
    if (URL_ATTRIBUTES.has(key)) {
      const href = safeUrl(value);
      if (href === null) continue;
      value = href;
    }
    attributes.push(key + '="' + escapeHtml(value) + '"');
  }
  const open = "<" + name + (attributes.length ? " " + attributes.join(" ") : "");
  return open + (VOID_TAGS.has(name) || /\/>$/.test(raw) ? " />" : ">");
};

// A tag or an HTML comment. Quoted attribute values are consumed whole so a ">"
// inside one cannot end the tag early, and the letter after "<" is what lets a
// sentence like "a < b" through untouched.
const HTML_TOKEN = /<!--[\s\S]*?-->|<\/?[a-zA-Z][a-zA-Z0-9-]*(?:"[^"]*"|'[^']*'|[^"'>])*>/g;

const emphasise = (text: string): string => {
  let out = text.replace(/!\[([^\]]*)\]\(([^)\s]+)[^)]*\)/g, (_match, alt: string, src: string) => {
    const href = safeUrl(src);
    return href === null ? "" : '<img src="' + href + '" alt="' + alt + '" loading="lazy" />';
  });
  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)[^)]*\)/g, (_match, label: string, url: string) => {
    const href = safeUrl(url);
    return href === null ? label : '<a href="' + href + '">' + label + '</a>';
  });
  return out
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/__([^_]+)__/g, "<strong>$1</strong>")
    .replace(/(^|[^*])\*([^*\n]+)\*/g, "$1<em>$2</em>")
    .replace(/~~([^~]+)~~/g, "<del>$1</del>");
};

// Everything that is NOT recognised markup is escaped before any markdown runs,
// so text written in a post can never emit markup of its own.
const renderTokens = (text: string): string => {
  let out = "";
  let last = 0;
  let match: RegExpExecArray | null;
  HTML_TOKEN.lastIndex = 0;
  while ((match = HTML_TOKEN.exec(text)) !== null) {
    out += emphasise(escapeHtml(text.slice(last, match.index)));
    last = match.index + match[0].length;
    // A comment is invisible in HTML. Escaping one printed "<!-- editor note -->"
    // on the reader's screen as a paragraph of the post.
    if (match[0].slice(0, 4) !== "<!--") out += sanitizeTag(match[0]);
  }
  return out + emphasise(escapeHtml(text.slice(last)));
};

// The capturing group makes split() keep the code spans, so they land on the odd
// indexes and are the only parts emphasis and tag recognition are NOT applied to.
// Splitting rather than swapping in a placeholder means no post can ever contain
// something that collides with the placeholder.
const CODE_SPAN = /(`[^`]+`)/;

const inline = (text: string): string =>
  String(text == null ? "" : text)
    .split(CODE_SPAN)
    .map((part, index) =>
      index % 2 === 1 ? "<code>" + escapeHtml(part.slice(1, -1)) + "</code>" : renderTokens(part),
    )
    .join("");

const FENCE = /^\s{0,3}```/;
const HEADING = /^(#{1,6})\s+(.+)$/;
const QUOTE = /^\s{0,3}>/;
const RULE = /^\s{0,3}(?:-\s*){3,}$|^\s{0,3}(?:\*\s*){3,}$|^\s{0,3}(?:_\s*){3,}$/;
const TABLE_DIVIDER = /^\s*\|?[\s:|-]+\|[\s:|-]*$/;

// A block that opens with block-level markup is emitted as markup, not wrapped
// in a paragraph: <p><figure>…</figure></p> is invalid nesting and the browser
// silently closes the paragraph early, which reorders the page around it.
const HTML_BLOCK =
  /^\s{0,3}<(?:!--|\/?(?:address|article|aside|blockquote|dd|details|div|dl|dt|figcaption|figure|footer|form|h[1-6]|header|hr|iframe|main|nav|ol|p|picture|pre|script|section|style|summary|table|tbody|td|tfoot|th|thead|tr|ul|video)\b)/i;

// Groups: 1 indent, 2 bullet character, 3 digits, 4 ordered delimiter, 5 the gap,
// 6 the content. The two marker forms are separate groups because which one
// matched is the only thing that says ordered or unordered.
const LIST_ITEM = /^(\s*)(?:([-*+])|(\d{1,9})([.)]))(\s+)(.*)$/;

const indentWidth = (line: string): number => {
  let width = 0;
  for (let i = 0; i < line.length; i++) {
    if (line[i] === " ") width += 1;
    else if (line[i] === "\t") width += 4;
    else break;
  }
  return width;
};

// Take a nested item's own indentation off its lines, so they can be rendered as
// a document of their own.
const dedent = (line: string, column: number): string => {
  let i = 0;
  let width = 0;
  while (i < line.length && width < column) {
    if (line[i] === " ") width += 1;
    else if (line[i] === "\t") width += 4;
    else break;
    i++;
  }
  return line.slice(i);
};

// "- - -" is a horizontal rule AND matches the bullet pattern. Rules win.
const listItemAt = (line: string): RegExpExecArray | null =>
  RULE.test(line) ? null : LIST_ITEM.exec(line);

// "-" / "*" / "+" / "." / ")". Changing the marker starts a NEW list, which is
// the only thing keeping a bullet list and a numbered list written directly
// under it from merging into one.
const listKind = (item: RegExpExecArray): string =>
  item[2] !== undefined ? item[2] : item[4];

// A line that opens a block of its own, so it ends the list rather than
// continuing the item above it.
const interruptsList = (line: string): boolean =>
  FENCE.test(line) || HEADING.test(line) || RULE.test(line) || QUOTE.test(line) || HTML_BLOCK.test(line);

// Deep enough for any real article; the bound is what stops a pathological file
// recursing until the build process runs out of stack.
const MAX_LIST_DEPTH = 6;

/**
 * Every line belonging to one list, from its first marker to the line that ends
 * it. Blank lines between items are KEPT.
 *
 * Stopping at the first blank line is what made "1. one" / blank / "2. two" /
 * blank / "3. three" come out as three separate <ol> elements, so the reader saw
 * "1. one / 1. two / 1. three" — while the same article published to WordPress,
 * Ghost and Webflow numbered it 1, 2, 3.
 */
const collectList = (
  lines: string[],
  from: number,
  first: RegExpExecArray,
): { block: string[]; next: number } => {
  const base = indentWidth(lines[from]);
  const kind = listKind(first);
  const block: string[] = [];
  let i = from;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === "") {
      let ahead = i + 1;
      while (ahead < lines.length && lines[ahead].trim() === "") ahead++;
      if (ahead >= lines.length) break;
      const next = listItemAt(lines[ahead]);
      const width = indentWidth(lines[ahead]);
      // Past a blank line the list continues only into a nested item, an
      // indented continuation, or a sibling carrying the same marker.
      const continues = next
        ? width > base || (width === base && listKind(next) === kind)
        : width > base;
      if (!continues) break;
      block.push("");
      i = ahead;
      continue;
    }
    const item = listItemAt(line);
    const width = indentWidth(line);
    if (item) {
      if (width < base || (width === base && listKind(item) !== kind)) break;
      block.push(line);
      i++;
      continue;
    }
    if (width <= base && interruptsList(line)) break;
    // Indented, or simply the next line of the same sentence. Both belong to the
    // item above.
    block.push(line);
    i++;
  }
  while (block.length > 0 && block[block.length - 1].trim() === "") block.pop();
  return { block, next: i };
};

/**
 * One <li>. A loose list wraps each item's own text in <p>, which is what a
 * blank line between items means and what every other renderer this product
 * publishes through does.
 */
const renderListItem = (
  lines: string[],
  loose: boolean,
  depth: number,
): string => {
  let cut = lines.length;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "" || listItemAt(lines[i]) || FENCE.test(lines[i]) || HTML_BLOCK.test(lines[i])) {
      cut = i;
      break;
    }
  }
  const lead = lines
    .slice(0, cut)
    .map((line) => line.trim())
    .filter(Boolean)
    .join(" ");
  const rest = lines.slice(cut);
  const head = lead === "" ? "" : loose ? "<p>" + inline(lead) + "</p>" : inline(lead);
  const tail = rest.length > 0 ? markdownToHtml(rest.join("\n"), depth + 1) : "";
  return "<li>" + head + (tail === "" ? "" : (head === "" ? "" : "\n") + tail) + "</li>";
};


interface ListItemLines {
  /** Where this item's content starts, so its continuation lines can be dedented. */
  column: number;
  lines: string[];
}

const renderList = (
  block: string[],
  first: RegExpExecArray,
  depth: number,
): string => {
  const base = indentWidth(block[0]);
  const kind = listKind(first);
  const ordered = first[3] !== undefined;
  const start = ordered && first[3] !== "1" ? ' start="' + String(Number(first[3])) + '"' : "";
  const items: ListItemLines[] = [];
  let loose = false;
  let blank = false;
  for (const line of block) {
    if (line.trim() === "") {
      if (items.length > 0) blank = true;
      continue;
    }
    const item = listItemAt(line);
    if (item && indentWidth(line) <= base && listKind(item) === kind) {
      if (items.length > 0 && blank) loose = true;
      blank = false;
      items.push({ column: line.length - item[6].length, lines: [item[6]] });
      continue;
    }
    if (items.length === 0) continue;
    const current = items[items.length - 1];
    if (blank) {
      current.lines.push("");
      loose = true;
      blank = false;
    }
    current.lines.push(dedent(line, current.column));
  }
  const body = items.map((item) => renderListItem(item.lines, loose, depth)).join("");
  return ordered ? "<ol" + start + ">" + body + "</ol>" : "<ul>" + body + "</ul>";
};

export const markdownToHtml = (markdown: string, depth: number = 0): string => {
  const lines = String(markdown == null ? "" : markdown).replace(/\r\n/g, "\n").split("\n");
  const html: string[] = [];
  let paragraph: string[] = [];

  const flush = () => {
    if (paragraph.length === 0) return;
    html.push("<p>" + inline(paragraph.join(" ")) + "</p>");
    paragraph = [];
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (FENCE.test(line)) {
      flush();
      const code: string[] = [];
      i++;
      while (i < lines.length && !FENCE.test(lines[i])) {
        code.push(lines[i]);
        i++;
      }
      html.push("<pre><code>" + escapeHtml(code.join("\n")) + "</code></pre>");
      continue;
    }

    if (line.trim() === "") {
      flush();
      continue;
    }

    if (HTML_BLOCK.test(line)) {
      flush();
      const block: string[] = [];
      while (i < lines.length && lines[i].trim() !== "") {
        block.push(lines[i]);
        i++;
      }
      i--;
      const rendered = inline(block.join("\n"));
      if (rendered.trim() !== "") html.push(rendered);
      continue;
    }

    const heading = HEADING.exec(line);
    if (heading) {
      flush();
      const level = String(heading[1].length);
      html.push("<h" + level + ">" + inline(heading[2].trim()) + "</h" + level + ">");
      continue;
    }

    if (RULE.test(line)) {
      flush();
      html.push("<hr />");
      continue;
    }

    if (QUOTE.test(line)) {
      flush();
      const quoted: string[] = [];
      while (i < lines.length && QUOTE.test(lines[i])) {
        quoted.push(lines[i].replace(/^\s{0,3}>\s?/, ""));
        i++;
      }
      i--;
      html.push("<blockquote><p>" + inline(quoted.join(" ")) + "</p></blockquote>");
      continue;
    }

    const item = depth < MAX_LIST_DEPTH ? listItemAt(line) : null;
    if (item) {
      flush();
      const list = collectList(lines, i, item);
      i = list.next - 1;
      html.push(renderList(list.block, item, depth));
      continue;
    }

    if (line.indexOf("|") !== -1 && i + 1 < lines.length && TABLE_DIVIDER.test(lines[i + 1])) {
      flush();
      const cells = (row: string): string[] =>
        row
          .replace(/^\s*\|/, "")
          .replace(/\|\s*$/, "")
          .split("|")
          .map((cell) => inline(cell.trim()));
      const head = cells(line).map((cell) => "<th>" + cell + "</th>").join("");
      const rows: string[] = [];
      i += 2;
      while (i < lines.length && lines[i].indexOf("|") !== -1 && lines[i].trim() !== "") {
        rows.push("<tr>" + cells(lines[i]).map((cell) => "<td>" + cell + "</td>").join("") + "</tr>");
        i++;
      }
      i--;
      html.push("<table><thead><tr>" + head + "</tr></thead><tbody>" + rows.join("") + "</tbody></table>");
      continue;
    }

    paragraph.push(line.trim());
  }

  flush();
  return html.join("\n");
};
