// Reading the posts. They are files in this repository, so publishing one is a
// commit and your host rebuilds the site the way it always has.
//
// Generated by SearchBlueprint. Safe to edit — it is your file now.
import fs from "fs";
import path from "path";
import { markdownToHtml, parseFrontMatter } from "./markdown";

const POSTS_DIR = path.join(process.cwd(), "content", "blog");

export interface PostSummary {
  slug: string;
  title: string;
  description: string;
  /** The timestamp as written in the file, for machines. */
  date: string;
  /** The same date for people, e.g. "March 4, 2026". */
  dateLabel: string;
}

export interface Post extends PostSummary {
  /** The body of the post, already rendered to HTML. */
  html: string;
}

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

// Built from the UTC parts on purpose. toLocaleDateString() uses the build
// machine's timezone, so a post stamped at midnight UTC would show the previous
// day on any server west of it.
const formatDate = (iso: string): string => {
  const at = new Date(iso);
  if (isNaN(at.getTime())) return "";
  return MONTHS[at.getUTCMonth()] + " " + String(at.getUTCDate()) + ", " + String(at.getUTCFullYear());
};

const POST_FILE = /\.mdx?$/i;

// Also the guard that stops a slug like ../../secrets reaching path.join().
const SAFE_SLUG = /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/;

// The page prints the title itself, so a leading heading in the body would be a
// second H1 on the same page: visibly duplicated, and a genuine SEO problem.
const stripLeadingHeading = (body: string): string => body.replace(/^\s*#\s+[^\n]*\n?/, "");

const titleFromBody = (body: string): string => {
  const heading = /^\s*#\s+([^\n]+)/.exec(body);
  return heading ? heading[1].trim() : "";
};

const titleFromSlug = (slug: string): string =>
  slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

// A missing or empty posts folder is the NORMAL state immediately after setup:
// nothing has been published yet. It renders an empty blog and must never fail
// the build.
const listFiles = (): string[] => {
  try {
    return fs.readdirSync(POSTS_DIR).filter((name) => POST_FILE.test(name));
  } catch {
    return [];
  }
};

const readPost = (fileName: string): Post | null => {
  const slug = fileName.replace(POST_FILE, "");
  if (!SAFE_SLUG.test(slug)) return null;
  let raw = "";
  try {
    raw = fs.readFileSync(path.join(POSTS_DIR, fileName), "utf8");
  } catch {
    return null;
  }
  const parsed = parseFrontMatter(raw);
  const date = parsed.data.date || "";
  return {
    slug,
    title: parsed.data.title || titleFromBody(parsed.body) || titleFromSlug(slug),
    description: parsed.data.description || parsed.data.excerpt || "",
    date,
    dateLabel: formatDate(date),
    html: markdownToHtml(stripLeadingHeading(parsed.body)),
  };
};

const isPost = (post: Post | null): post is Post => post !== null;

/** Newest first. A post with no date sorts last rather than disappearing. */
export const getAllPosts = (): PostSummary[] =>
  listFiles()
    .map(readPost)
    .filter(isPost)
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.title.localeCompare(b.title)))
    .map((post) => ({
      slug: post.slug,
      title: post.title,
      description: post.description,
      date: post.date,
      dateLabel: post.dateLabel,
    }));

export const getPostBySlug = (slug: string): Post | null => {
  if (!SAFE_SLUG.test(slug || "")) return null;
  return readPost(slug + ".mdx") || readPost(slug + ".md");
};
