// The blog's styling, kept out of the route files so both of them share it.
//
// Rendered inside a <style> element rather than imported as a .css file: a
// global stylesheet import is only legal from _app in the Pages Router, and a
// CSS Module cannot reach markup rendered from an HTML string.
//
// Generated by SearchBlueprint. Safe to edit — it is your file now.
export const blogStyles = [
  ".sb-blog{max-width:44rem;margin:0 auto;padding:3.5rem 1.25rem 4.5rem;color:var(--foreground, inherit);line-height:1.7;font-size:1.0625rem}",
  ".sb-blog h1,.sb-blog h2,.sb-blog h3{line-height:1.2;letter-spacing:-0.015em}",
  ".sb-blog h1{font-size:clamp(2rem,5vw,2.75rem);font-weight:700;margin:0 0 0.75rem}",
  ".sb-blog h2{font-size:1.5rem;font-weight:600;margin:2.5rem 0 0.75rem}",
  ".sb-blog h3{font-size:1.2rem;font-weight:600;margin:2rem 0 0.5rem}",
  ".sb-blog p,.sb-blog ul,.sb-blog ol,.sb-blog blockquote,.sb-blog table,.sb-blog pre{margin:0 0 1.25rem}",
  ".sb-blog ul,.sb-blog ol{padding-left:1.25rem}",
  ".sb-blog li{margin:0 0 0.4rem}",
  ".sb-blog a{color:var(--accent, inherit);text-decoration:underline;text-underline-offset:0.15em}",
  ".sb-blog-lede{opacity:0.72;margin:0 0 2.75rem}",
  ".sb-blog-meta{display:block;opacity:0.65;font-size:0.9rem;margin:0 0 2rem}",
  ".sb-blog-empty{opacity:0.7}",
  ".sb-blog-list{list-style:none;margin:0;padding:0}",
  ".sb-blog-item{padding:0 0 2rem;margin:0 0 2rem;border-bottom:1px solid rgba(127,127,127,0.28)}",
  ".sb-blog-item:last-child{border-bottom:0;margin-bottom:0}",
  ".sb-blog-item h2{margin:0 0 0.35rem;font-size:1.35rem}",
  ".sb-blog-item a{display:inline-block;min-height:2.75rem;padding:0.35rem 0;text-decoration:none}",
  ".sb-blog-item a:hover{text-decoration:underline}",
  ".sb-blog-item p{margin:0 0 0.35rem;opacity:0.82}",
  ".sb-blog-item .sb-blog-meta{margin:0}",
  ".sb-blog-body img{max-width:100%;height:auto;display:block;border-radius:0.5rem;margin:1.75rem 0}",
  ".sb-blog-body pre{overflow-x:auto;padding:1rem 1.1rem;border-radius:0.6rem;background:rgba(127,127,127,0.12);font-size:0.9rem;line-height:1.6}",
  ".sb-blog-body code{font-family:var(--font-mono);font-size:0.92em}",
  ".sb-blog-body p code,.sb-blog-body li code{background:rgba(127,127,127,0.12);padding:0.1rem 0.3rem;border-radius:0.3rem}",
  ".sb-blog-body blockquote{margin-left:0;padding:0.15rem 0 0.15rem 1.1rem;border-left:3px solid rgba(127,127,127,0.28);opacity:0.9}",
  ".sb-blog-body table{border-collapse:collapse;width:100%;display:block;overflow-x:auto;font-size:0.95rem}",
  ".sb-blog-body th,.sb-blog-body td{border:1px solid rgba(127,127,127,0.28);padding:0.5rem 0.65rem;text-align:left}",
  ".sb-blog-body hr{border:0;border-top:1px solid rgba(127,127,127,0.28);margin:2.5rem 0}",
  ".sb-blog-back{display:inline-block;min-height:2.75rem;padding:0.6rem 0;margin:2.75rem 0 0;text-decoration:none}",
  ".sb-blog-back:hover{text-decoration:underline}",
  "@media (max-width:640px){.sb-blog{padding:2.5rem 1.1rem 3.5rem;font-size:1rem}}",
].join("");
